spring:
  application:
    name: learn-spring

logging:
  level:
    org:
      springframework: info

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - metrics