spring:
  application:
    name: learn-spring
  profiles:
    active: dev

logging:
  level:
    org:
      springframework: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"